# Generated by Django 5.2.9 on 2026-01-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lowstockalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowstockalert',
            options={'permissions': [('view_low_stock_alert', 'Can view low stock alerts'), ('resolve_low_stock_alert', 'Can resolve low stock alerts')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('adjust_stock', 'Can adjust product stock'), ('view_cost_price', 'Can view product cost price'), ('discontinue_product', 'Can discontinue product')]},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ('-timestamp',), 'permissions': [('create_stock_transaction', 'Can create stock transaction'), ('approve_stock_transaction', 'Can approve stock transaction'), ('view_stock_history', 'Can view stock transaction history')]},
        ),
    ]
