# Generated by Django 5.2.10 on 2026-01-14 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_lowstockalert_options_alter_product_options_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowstockalert',
            old_name='created_at',
            new_name='triggered_at',
        ),
        migrations.RemoveField(
            model_name='lowstockalert',
            name='message',
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='reorder_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.CreateModel(
            name='StockReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_entry', to='inventory.lowstockalert')),
            ],
        ),
    ]
