# Generated by Django 5.2.10 on 2026-02-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_created_at_lowstockalert_triggered_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockReportEntry',
        ),
    ]
