# Generated by Django 5.2.6 on 2025-12-31 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lowstockalert'),
        ('orders', '0003_purchaseorderitem_line_status_orderstatushistory'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesOrder',
            new_name='SaleOrder',
        ),
        migrations.RenameModel(
            old_name='SalesOrderItem',
            new_name='SaleOrderItem',
        ),
    ]
