# Generated by Django 5.2.10 on 2026-06-13 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in +855xxxxxxxx format.', regex='^\\+855\\d{8,9}$')]),
        ),
    ]
