# Generated by Django 5.2.6 on 2026-01-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_salesorder_saleorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='warehouse',
        ),
    ]
