# Generated by Django 5.2.9 on 2026-01-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_purchaseorderitem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('view_purchase_order', 'Can view purchase orders'), ('create_purchase_order', 'Can create purchase orders'), ('confirm_purchase_order', 'Can confirm purchase orders'), ('receive_purchase_order', 'Can receive purchase orders'), ('cancel_purchase_order', 'Can cancel purchase orders')]},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('view_sale_order', 'Can view sales orders'), ('create_sale_order', 'Can create sales orders'), ('confirm_sale_order', 'Can confirm sales orders'), ('ship_sale_order', 'Can ship sales orders'), ('invoice_sale_order', 'Can invoice sales orders'), ('cancel_sale_order', 'Can cancel sales orders')]},
        ),
    ]
