# Generated by Django 5.2.9 on 2026-01-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_purchaseorder_options_alter_saleorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('confirm_sale_order', 'Can confirm sales orders'), ('ship_sale_order', 'Can ship sales orders'), ('invoice_sale_order', 'Can invoice sales orders'), ('cancel_sale_order', 'Can cancel sales orders')]},
        ),
    ]
