# Generated by Django 5.2.9 on 2026-01-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_saleorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('confirm_purchase_order', 'Can confirm purchase orders'), ('receive_purchase_order', 'Can receive purchase orders'), ('cancel_purchase_order', 'Can cancel purchase orders')]},
        ),
    ]
