# Generated by Django 5.2.9 on 2026-01-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('confirm_purchaseorder', 'Can confirm purchase orders'), ('receive_purchaseorder', 'Can receive purchase orders'), ('cancel_purchaseorder', 'Can cancel purchase orders')]},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('confirm_saleorder', 'Can confirm sales orders'), ('ship_saleorder', 'Can ship sales orders'), ('invoice_saleorder', 'Can invoice sales orders'), ('cancel_saleorder', 'Can cancel sales orders')]},
        ),
    ]
