# Generated by Django 5.2.9 on 2026-01-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_purchaseorder_options_alter_saleorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('confirm_purchase_order', 'Can confirm purchase orders'), ('receive_purchase_order', 'Can receive purchase orders'), ('cancel_purchase_order', 'Can cancel purchase orders')]},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('confirm_sale_order', 'Can confirm sales orders'), ('ship_sale_order', 'Can ship sales orders'), ('invoice_sale_order', 'Can invoice sales orders'), ('cancel_sale_order', 'Can cancel sales orders')]},
        ),
    ]
