# Generated by Django 5.2.6 on 2025-09-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransaction'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='warehouses.warehouse'),
        ),
    ]
