# Generated by Django 5.2.10 on 2026-07-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_customers', 'Can edit or deactivate customer records')]},
        ),
    ]
