# Generated by Django 5.2.6 on 2026-01-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lowstockalert'),
        ('reports', '0004_purchasereportentry_salesreportentry_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lowstockalert',
            unique_together={('product', 'warehouse')},
        ),
    ]
