# Generated by Django 5.2.10 on 2026-07-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_lowstockalert_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['-created_at'], 'permissions': [('view_reports', 'Can view reports')]},
        ),
    ]
