# Generated by Django 5.2.10 on 2026-01-14 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_lowstockalert_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowstockalert',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowstockalert',
            name='reorder_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockreportentry',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_entry', to='reports.lowstockalert'),
        ),
        migrations.AlterField(
            model_name='stockreportentry',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
